spring:
  profiles: mysql
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/raindb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:rain}
    password: ${SPRING_DATASOURCE_PASSWORD:rainpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
